### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by pieterclaerhout** [matryer/crunchcrunchcrunchstack#1]
This looks like a really good way to get started, but I'm missing instructions on how to run / debug / build…

**Comment by mikejoh** [comment]
@pieterclaerhout I did the following to get this up and running, please note that I haven't worked with Node.js (or any part of this stack) before. If you're starting from scratch like me:

1. Install [`nvm`](https://github.com/nvm-sh/nvm):
```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
```
2. Install the LTS version of Node.js:
```
nvm install v14.17.0
```
3. Clone this repository.
4. With [`npm`](https://www.npmjs.com/get-npm), install the package and the dependencies specified in the `package.json` file:
```
npm install
```
5. Build:
```
npm run build
```
6. Run the server:
```go
go run main.go handle_greeter.go routes.go
```
7. Browse to `localhost:8080`.

That is enough to get started! :smiley:
